name: FlagGames
version: 1.0.0
authors: [kojima1021, mozipi, mrT_japan]
website: http://wiki.mcmmorpg-server.net
main: mcmmorpggroup.flaggames.FlagGame
database: false
commands:
   Killplayer:
      description: コマンドでプレーヤーを殺すコマンドです。
      usage: /Killplayer <player>
      permision: FlagGame.admin.kill
      permision-message: You don't have FlagGame.admin.kill
   tpall:
      description: コマンドで全プレーヤーを自分の場所に呼ぶコマンドです。
      usage: /tpall
      permision: FlagGame.admin.tpall
      permision-message: You don't have FlagGame.admin.tpall