name: FlagGames
version: 1.0.0
authors: [kojima1021, mozipi, mrT_japan, Creepapa]
website: http://wiki.mcmmorpg-server.net
main: mcmmorpggroup.flaggames.FlagGame
commands:
   flaggames:
      description: FlagGamesのコマンドです。
      usage: /flaggames
      permision-message: You don't have permission!
   fg:
      description: FlagGamesのコマンドです。
      usage: /fg
      permision-message: You don't have permission!